<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Contains types and interfaces that are used to interact with the dispatcher and runtime</Description>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <Version>1.0.0-alpha1</Version>
        <PackageTags>Innovation; CQRS; Mediator; Command; Query; Dispatcher; RequestResponse</PackageTags>
        <PackageReleaseNotes>https://github.com/louislewis2/innovation-vnext/releases</PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    </ItemGroup>
</Project>