<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Contains Helpers For Asp.Net Core. Dispatching Base Class And Correlation Id Support</Description>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <Version>1.0.0-alpha1</Version>
        <PackageTags>Innovation; CQRS; Mediator; AspNetCore; Controller; CorrelationId</PackageTags>
        <PackageReleaseNotes>https://github.com/louislewis2/innovation-vnext/releases</PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Innovation.Api.vNext\Innovation.Api.vNext.csproj" />
        <ProjectReference Include="..\Innovation.ServiceBus.InProcess.vNext\Innovation.ServiceBus.InProcess.vNext.csproj" />
    </ItemGroup>

</Project>
